### ISSUE TITLE
Expandable rows in measure table

### ISSUE THREAD

**Issue by hutschen** [hutschen/mv-tool-ng#70]
Add a feature to allow measure rows in tables to be expanded, displaying the full text of the measure for better readability and user experience.

**Comment by hutschen** [comment]
Perhaps this feature can be implemented by creating a new CSS class that overrides the effects of the `truncate` and `truncate-lines` classes. This would mean that all elements that have both the `truncate` and `truncate-lines` classes within an element (see `shared/styles/truncate.scss`) are expanded.

```css
.disable-truncation .truncate,
.disable-truncation .truncate-lines {
  overflow: unset !important;
  text-overflow: unset !important;
  white-space: unset !important;
  -webkit-line-clamp: unset !important;
}
```

This definition of `disable-truncation` removes truncation for all child elements with .truncate and .truncate-lines classes if the parent element has .disable-truncation class. It also removes truncation for the element itself.
